sbcl: Filter out invalid definition sources in find-definitions
They can't be visited, so filtering them eliminates this error:

    Error: DEFINITION-SOURCE of blah did not contain meaningful
    information

This commonly arises when a method is defined without a corresponding
defgeneric.